# =============================================================================
# @file    archive-github-pages.yml
# @brief   Save the Github pages in the Internet Archive
# @author  Michael Hucka <mhucka@caltech.edu>
# @license Please see the file named LICENSE in the repository
# @repo    https://github.com/caltechlibrary/foliage
# =============================================================================

on:
  release:
    types: [published]
jobs:
  Workflow:
    uses: caltechlibrary/waystation@main
    with:
      debug: true
