# =============================================================================
# @file    build-myst.yml
# @brief   GitHub Actions workflow to build FOLIAGE docs using MyST 
# @author  Michael Hucka <mhucka@caltech.edu>
# @license Please see the file named LICENSE in the project directory
# @website https://github.com/caltechlibrary/foliage
#
# This workflow file was originally based on work by GitHub user "peaceiris":
# https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-static-site-generators-with-python
# =============================================================================

name: Build & publish Sphinx docs

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  Workflow:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Upgrade pip
        run: |
          # Need pip=>20.1 to use "pip cache dir".
          python3 -m pip install --upgrade pip

      - name: Get pip cache dir
        id: pip-cache
        run: echo "dir=$(pip cache dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements-dev.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: python3 -m pip install -r ./requirements-dev.txt

      - name: Generate HTML files
        run: |
          cd docs
          make html

      - name: Publish HTML files on GitHub pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html
